// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vknsxlhucegikbfufbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbnN4bGh1Y2VnaWtiZnVmYmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTk1MzUsImV4cCI6MjA1OTMzNTUzNX0.wiPcwnaRyV7HZXwyXc5x7D9tOM9zoD46BsuzPM5KAfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);